# Generated by Django 3.2 on 2024-02-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('religion', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
